### ISSUE TITLE
【bug】从浏览器拖入后，不能立刻查看

### ISSUE THREAD

**Issue by bingling00** [hunmer/mCollection#11]
## 问题描述

从浏览器拖入后，不能立刻查看。点击图片无反应。

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Object.getFileType (format.js:33:10)
    at getFileType (format.js:50:21)
    at Object.item_getVal (dataitem.js:312:22)
    at async Object.on (preview.js:208:36)
    at async plugins.js:469:25
```

## 环境信息

请提供以下信息：

- 软件版本：1.0.1
- 操作系统：win11
- 截图（如果适用）：
![image](https://github.com/hunmer/mCollection/assets/61322616/24fbbd2e-eb95-4e8d-a2a7-ae9a10ce71e6)

## 其他信息

请勾选以下选项(括号内输入x,例如[x])：

- [x] 已经阅读了常见问题
- [x] 已经搜索了现有的 Issue

## 复现步骤

请提供复现该问题的详细步骤。

1. 步骤 1 ：拖动图片到软件界面
2. 步骤 2 ：双击图片

## 预期行为

双击打开图片

## 实际行为

无反应

**Comment by amlkiller** [comment]
![image](https://github.com/hunmer/mCollection/assets/62412330/4dec8076-0a67-4db3-bd3d-e304693e052c)
我这也有一样都问题，我认为是根本没导入进去。

**Comment by bingling00** [comment]
> 

我的是导入了，你关了重进，应该是有的。

**Comment by amlkiller** [comment]
> > 
> 
> 我的是导入了，你关了重进，应该是有的。

已经尝试了，是没有，是和素材类型有关吗？我用的是视频。能看到建立了数据库，但显然没有数据。
![image](https://github.com/hunmer/mCollection/assets/62412330/4e10765e-a431-41a9-a029-cc0248cabefa)

**Comment by amlkiller** [comment]
进去Q群看了下，重新装了后别更新就行

**Comment by hunmer** [comment]
已修复
