### ISSUE TITLE
素材重命名问题

### ISSUE THREAD

**Issue by brucevlw** [hunmer/mCollection#16]
## 问题描述
没找到在哪里重命名图片

## 环境信息

请提供以下信息：

- 软件版本：20230627 
- 操作系统：windows11
- 截图（如果适用）：

## 其他信息

请勾选以下选项(括号内输入x,例如[x])：

- [x] 已经阅读了常见问题
- [x] 已经搜索了现有的 Issue

## 复现步骤

请提供复现该问题的详细步骤。

1. 步骤 1
2. 步骤 2
3. 步骤 3

## 预期行为

1. 可以以为可以右键有重命名；
2. 期待有右键重命名而没找到后，去文件所在数据库文件夹的位置修改了文件名，但回来刷新后还是没重命名成功，挺疑惑。

## 实际行为

请描述实际上发生的行为。

**Comment by hunmer** [comment]
右侧信息栏里标题那一栏默认名称可以更改
