### ISSUE TITLE
打开软件提示更新，更新后无法使用

### ISSUE THREAD

**Issue by MillionZBW** [hunmer/mCollection#2]
![image](https://github.com/hunmer/mCollection/assets/23210456/109e930e-c6a9-4327-8040-3b61660b1b81)
如图，更新后重新打开软件界面无内容，软件右上角三色按钮无响应。系统右下角图标右键退出会卡死。

**Comment by hunmer** [comment]
更新一下客户端，新版本已经上传至[Releases](https://github.com/hunmer/mCollection/releases)，可以覆盖或者解压使用
