### ISSUE TITLE
MACOS 无法导入素材

### ISSUE THREAD

**Issue by FrankK-Fan** [hunmer/mCollection#25]
感谢hunmer大大

刚刚发现宝藏工具，看到的功能和想象中非常一致。但是我小白纯新，安装后，没法导入素材。是操作的问题吗？还是我设置的问题。
1、我是采用的链接方式导入素材
2、采用了两种方式导入。直接拖拽的方式和安装了导入插件选择路径的方式 均不成功。
3、点击后，能看到下方蓝色金典条显示数字

其余没有了 再次感谢

- 软件版本：版本1.0.0 (1.0.0)
- 操作系统：MACOS13.3

## 其他信息

- [x ] 已经阅读了常见问题
- [ x] 已经搜索了现有的 Issue

**Comment by hunmer** [comment]
创建库了吗？软件截图/录屏看看

**Comment by FrankK-Fan** [comment]
创建了
<img width="526" alt="截屏2024-11-06 16 10 30" src="https://github.com/user-attachments/assets/adcfb8aa-9786-462d-9c9c-af7baf3ff1f3">
<img width="1366" alt="截屏2024-11-06 16 11 06" src="https://github.com/user-attachments/assets/4add4b24-3e3f-4e8d-8503-d60a070adc6a">
<img width="1367" alt="截屏2024-11-06 16 15 07" src="https://github.com/user-attachments/assets/c8c4d1a4-7141-448f-96ff-9722a198a06e">

**Comment by hunmer** [comment]
多大的文件？按F12->console看看报错信息

**Comment by FrankK-Fan** [comment]
感谢大佬  文件大小都试过 有几M也有几百M  都不太行  图片也不行。这个是报错的截图
<img width="547" alt="截屏2024-11-06 16 35 46" src="https://github.com/user-attachments/assets/3a5fb764-714e-4785-91d1-b9e7e1abb20a">
<img width="543" alt="截屏2024-11-06 16 37 01" src="https://github.com/user-attachments/assets/20a471fd-ae07-406d-acbd-3ff4907887be">

**Comment by hunmer** [comment]
你把压缩包解压到哪里了？你需要用原版解压程序解压到applications目录下(macos默认的目录)

**Comment by FrankK-Fan** [comment]
大佬  刚刚又重新试了几遍。还是不太行。原来的方式是解压到下载文件夹，然后拷贝到《应用程序》那个文件夹里。（原版的归档实用工具解压出来的打不开，用betterzip解压可以打开）这样会出现导入不了的问题。
您说的《applications目录下》是《应用程序》吗？还是在别的地方？
打开以后是这样的 正常吗？
实在是小白 不太懂 麻烦了哈
<img width="790" alt="截屏2024-11-06 17 16 18" src="https://github.com/user-attachments/assets/aca6a54c-9582-4a73-8adc-9452c63424b4">

**Comment by hunmer** [comment]
实在不行加下QQ群，远程看看

**Comment by FrankK-Fan** [comment]
好的好的  感谢
