### ISSUE TITLE
发现一些问题

### ISSUE THREAD

**Issue by MillionZBW** [hunmer/mCollection#3]
感谢作者辛苦捉虫。问题如下
1：应用启动器显示更新成功，但是重启应用后发现实际未更新成功。（未找到刷新应用功能，所以选择了重启应用）
2：公共库更新会卡89%，无论是否科学上网。（图1）
3：自定义壁纸不生效。
4：清空回收站成功，但是文件管理器里查看，文件实际还在并未删除。
5：素材管理器的左上角“+”点击无效。
6：素材右键，“设置封面”和“打开目录”均无效
7：视频素材，鼠标单击，会发现视频预览画面超出框选范围。且视频预览时，鼠标移开后，该框选会有个拉伸，不好看。
8：素材管理器左侧三点按钮点击会偶发空白菜单（图2）
9：素材管理器左侧删除标签，素材详情页标签不会消失，而是显示“undefined”。而且“拼音”里的首字母分类里还依然保留了已删除的项目。
10：素材详情页添加新的标签，按下回车不能直接显示出来标签。（图3）
11：素材管理器左侧，项目太多时，会和设置、插件按钮重合。
12：素材详情页似乎会显示出来素材包含的颜色，我感觉是按颜色分类？但是点击颜色素材都消失了，暂且当bug反馈吧。
13：切换视图会丢素材（左侧数量显示无误，切换信息排序又出现了）。似乎“信息”“排序”“视图”的功能都有问题，不生效，貌似功能还没写好一样。

一些建议：
1：主界面启动过的项目能记住窗口大小，每次都是全屏，需要手动缩小。
2：考虑到需求只有素材管理器，希望能增加“启动时打开自定义应用或启动最后打开的应用”。
3：我发现文件都是复制到资源库的目录下的。能不能有不动文件只添加到素材库的方式呢？（因为我文件都是自己分类放的，素材管理器更多是为了标签。虽然觉得可能性不大，还是提一嘴。）另外就牵扯到复制到素材库后还要手动删一下之前的文件的问题了，觉得这样有点麻烦。
4：根据预设的“浏览器导入”，能不能只要监视到该文件夹有新文件就自动导入呢？
5：素材详情页添加标签或群组时的弹窗，已选中的项目感觉有歧义，建议改成“已添加的标签”。“拼音”和“群组”前面要不加个分类文字吧（虽然这样一说就暴露我傻，但是一开始真的以为是方便切换文件夹和标签的）
6：我自己已经分类好的文件夹要能直接导入成一个素材库就好了。
7：素材详情页的添加标签或群组，实际是一个类似输入框，点击输入框进行编辑，但是图标有+，下意识会认为是点图标进行添加操作。建议就改成点击图标进行编辑，一是避免图标误导，二是避免点击已存在的标签时误触。（或者改一下颜色，和用户添加的标签颜色区分开）
8：打开一个应用就回不到主界面了，建议顶部加个打开主界面的按钮。

ps：真的很对不起，一开始就3条BUG，一边测试一边写就这么多了。
我的环境是Win11，软件为覆盖更新（解压路径是mLauncher/mLauncher_win10，但我把文件移动到了mLauncher，并删除了软件生成的文件夹mLauncher_win10）暂未使用任何插件。祝软件越来越好，star破百万。

<img width="664" alt="屏幕截图 2023-06-12 000622" src="https://github.com/hunmer/mCollection/assets/23210456/7bc0b718-d8b1-4ef0-915a-1c8e5691f863">
<img width="317" alt="屏幕截图 2023-06-12 003952" src="https://github.com/hunmer/mCollection/assets/23210456/cf8c9c4b-f3be-426f-9809-c61177c65592">
<img width="289" alt="屏幕截图 2023-06-12 010951" src="https://github.com/hunmer/mCollection/assets/23210456/85bc4593-d4c6-4c4c-93cf-d163091401e9">

**Comment by hunmer** [comment]
1，2，3，4，5已经修复了，更新文件逻辑错误导致更新无效，下载新上传的压缩包替换即可。

安装包也改成压缩包格式了，这样可以直接用winrar打开替换少许文件实现更新

在线更新增加了单文件下载进度，这样能够更清晰的判断是否为网络问题

自定义壁纸可以使用，但需要选择一款主题并且确保没有打开禁用背景选项（需优化）

设置封面还没写功能，打开目录已经修复了，但执行此操作可能会有几秒延迟

网格预览视频确实会超出，这个后面会优化成动画的展开视频。如果不想视频溢出，可以使用瀑布流布局

删除标签/文件夹，素材相关属性不消失已经修复。开发工具也会加入一键移除已过期的标签或者文件夹

详情页添加标签显示空名称已修复，左下角按钮重叠已修复，颜色查询已修复

排序之前正常的，现在出了点问题，之后修

------------

1.之后会计划记住窗口位置

2.你指的是跳过启动器直接打开素材库？之后支持将应用固定在任务栏图标右键启动菜单

3.如果只是想链接到素材库，可以在设置里设置素材库的导入方式为链接导入

4.自动导入之后会有相关的插件实现

5.弹窗添加标签/文件夹里的分类功能还没完善，等标签/文件夹管理功能完善后，支持插件添加其他分类（最近使用，最常使用等等）

6.可以安装【更多方式导入】插件，安装好之后，左上角菜单可以选择【连同目录一起导入到素材库】

7.现在点击默认的图标也会弹出设置标签/文件夹窗口

8.一个最简单的方法就是当前任务栏图标右键再打开一个窗口。其实如果要快速切换到其他应用的话，可以用插件实现无缝切换到其他启动器应用程序，之后会有计划


---------
ps：感谢反馈，在你安装了新版本后可以把应用都检测更新一边，最近兼容macos版本改动较大，更新可能较为频繁，如果有什么不懂的可以进群问

**Comment by adong3k** [comment]
标签无法删除
目录无法删除
标签费目录能不不能显示多一些，就几行，不好用
