### ISSUE TITLE
Mac M芯片的设备无法运行

### ISSUE THREAD

**Issue by dale502** [hunmer/mCollection#5]
现在的Mac Intel版安装后，无法打开

**Comment by hunmer** [comment]
下载压缩包解压后，没有显示应用图标吗？可以的话截下图跟系统的参数

**Comment by dale502** [comment]
<img width="180" alt="image" src="https://github.com/hunmer/mCollection/assets/69394230/10a9dae6-0a93-4d47-97b7-53ee5e0ea6ee">
<img width="250" alt="image" src="https://github.com/hunmer/mCollection/assets/69394230/83bc0498-f74a-4c24-ad01-ac8867bc2153">
解压正常，运行弹这个错误
M1 mac 13.4

**Comment by abcmiao** [comment]
可以啊，13.4，macOS M1

**Comment by xk756** [comment]
版本 12.2.1
MacBook Air (M1, 2020)

**Comment by hunmer** [comment]
试了一下确实无法打开，这次直接在macos上进行了打包上传，可以试试下载（20230613）：

https://github.com/hunmer/mCollection/releases/latest

**Comment by Charles0225** [comment]
您好，intel芯片Mac无法运行，程序已放入应用程序中
<img width="257" alt="截屏2024-06-19 15 03 14" src="https://github.com/hunmer/mCollection/assets/60239837/ce60e6f5-a5f0-4b55-9a56-f1185f1db646">
MacOS版本14.0

**Comment by hunmer** [comment]
> 您好，intel芯片Mac无法运行，程序已放入应用程序中 <img alt="截屏2024-06-19 15 03 14" width="257" src="https://private-user-images.githubusercontent.com/60239837/340960692-ce60e6f5-a5f0-4b55-9a56-f1185f1db646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODEwMDksIm5iZiI6MTcxODc4MDcwOSwicGF0aCI6Ii82MDIzOTgzNy8zNDA5NjA2OTItY2U2MGU2ZjUtYTVmMC00YjU1LTlhNTYtZjExODVmMWRiNjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGM3N2MwNmVkYTA4YzMwODk1Y2I5N2Y4NDQyZTY4NmQ5NDdhYWM0NDlkNDViODdkYmU3MjExN2QxMTgzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAioIv5RM0PJDNd_8YgEDSa4346WkMbYxKutomxXj6Y"> MacOS版本14.0

有提示什么吗？机器上有GPU吗？已知下个版本前无GPU无法正常启动

**Comment by Charles0225** [comment]
> > 您好，intel芯片Mac无法运行，程序已放入应用程序中 <img alt="截屏2024-06-19 15 03 14" width="257" src="https://private-user-images.githubusercontent.com/60239837/340960692-ce60e6f5-a5f0-4b55-9a56-f1185f1db646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODEwMDksIm5iZiI6MTcxODc4MDcwOSwicGF0aCI6Ii82MDIzOTgzNy8zNDA5NjA2OTItY2U2MGU2ZjUtYTVmMC00YjU1LTlhNTYtZjExODVmMWRiNjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGM3N2MwNmVkYTA4YzMwODk1Y2I5N2Y4NDQyZTY4NmQ5NDdhYWM0NDlkNDViODdkYmU3MjExN2QxMTgzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAioIv5RM0PJDNd_8YgEDSa4346WkMbYxKutomxXj6Y"> MacOS版本14.0
> 
> 有提示什么吗？机器上有GPU吗？已知下个版本前无GPU无法正常启动

提示如下
<img width="262" alt="截屏2024-06-19 16 16 35" src="https://github.com/hunmer/mCollection/assets/60239837/b1d67115-94fa-458c-b8de-6d565e85ebd0">
机器配置如下
<img width="277" alt="截屏2024-06-19 16 16 48" src="https://github.com/hunmer/mCollection/assets/60239837/7bb1b7dd-e792-4e39-8ffa-b360e35cbd75">
那应该是集显运行不了了，感谢

**Comment by hunmer** [comment]
> > > 您好，intel芯片Mac无法运行，程序已放入应用程序中 <img alt="截屏2024-06-19 15 03 14" width="257" src="https://private-user-images.githubusercontent.com/60239837/340960692-ce60e6f5-a5f0-4b55-9a56-f1185f1db646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODEwMDksIm5iZiI6MTcxODc4MDcwOSwicGF0aCI6Ii82MDIzOTgzNy8zNDA5NjA2OTItY2U2MGU2ZjUtYTVmMC00YjU1LTlhNTYtZjExODVmMWRiNjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGM3N2MwNmVkYTA4YzMwODk1Y2I5N2Y4NDQyZTY4NmQ5NDdhYWM0NDlkNDViODdkYmU3MjExN2QxMTgzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAioIv5RM0PJDNd_8YgEDSa4346WkMbYxKutomxXj6Y"> MacOS版本14.0
> > 
> > 
> > 有提示什么吗？机器上有GPU吗？已知下个版本前无GPU无法正常启动
> 
> 提示如下 <img alt="截屏2024-06-19 16 16 35" width="262" src="https://private-user-images.githubusercontent.com/60239837/340986663-b1d67115-94fa-458c-b8de-6d565e85ebd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODU0NzksIm5iZiI6MTcxODc4NTE3OSwicGF0aCI6Ii82MDIzOTgzNy8zNDA5ODY2NjMtYjFkNjcxMTUtOTRmYS00NThjLWI4ZGUtNmQ1NjVlODVlYmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNGQ4YmFjY2Q3MWU4YzYyYzNjZjFmMDk5NDc0YmQ1ZmI3ZGJlMGJjYTVmZjEzNWJmMDE3MzYzOTU4ODJhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtUa5XgDNe0UY2_vDZdiIDgcBJ8QwgFsFie_h5H3v1g"> 机器配置如下 <img alt="截屏2024-06-19 16 16 48" width="277" src="https://private-user-images.githubusercontent.com/60239837/340986797-7bb1b7dd-e792-4e39-8ffa-b360e35cbd75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODU0NzksIm5iZiI6MTcxODc4NTE3OSwicGF0aCI6Ii82MDIzOTgzNy8zNDA5ODY3OTctN2JiMWI3ZGQtZTc5Mi00ZTM5LThmZmEtYjM2MGUzNWNiZDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4MTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTM5ZmIxY2ZmN2FhYTU4ZTdmY2E1NjUwMDUzYTMzMDk3Zjk3YzU2NmUxYTU1NWY1ZjcwNDUxY2E2ODRkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws-CiQq8DmKk0tUVuXcIwgYN15ypz-A68jynJpHFt-U"> 那应该是集显运行不了了，感谢

好的，可以开windows虚拟机先尝鲜一下，后面更新了再回复你

**Comment by Charles0225** [comment]
> > 您好，intel芯片Mac无法运行，程序已放入应用程序中 <img alt="截屏2024-06-19 15 03 14" width="257" src="https://private-user-images.githubusercontent.com/60239837/340960692-ce60e6f5-a5f0-4b55-9a56-f1185f1db646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODEwMDksIm5iZiI6MTcxODc4MDcwOSwicGF0aCI6Ii82MDIzOTgzNy8zNDA5NjA2OTItY2U2MGU2ZjUtYTVmMC00YjU1LTlhNTYtZjExODVmMWRiNjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGM3N2MwNmVkYTA4YzMwODk1Y2I5N2Y4NDQyZTY4NmQ5NDdhYWM0NDlkNDViODdkYmU3MjExN2QxMTgzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAioIv5RM0PJDNd_8YgEDSa4346WkMbYxKutomxXj6Y"> MacOS版本14.0
> 
> 有提示什么吗？机器上有GPU吗？已知下个版本前无GPU无法正常启动

非常感谢！但我刚发现把设备序列号截图了==，方便的话麻烦删除一下上一条回复
