### ISSUE TITLE
某个公众号看到该软件，有些问题

### ISSUE THREAD

**Issue by iAngelovery** [hunmer/mCollection#8]
1，目前在用 Billfish ，当初从一点几版本就开始用，Eagle 据说会伤硬盘，就没用。就算不伤硬盘，听说 Eagle 的数据管理模式也很蛋疼。现在 Billfish 感觉在摆烂。官方应该是把精力放在企业版上去了，毕竟个人版不赚钱。
2、想问一下，数据的目录结构什么样子的，我个人是还比较喜欢 Billfish 这样的形势。不过标签之类的打的少。一般都是会在文件夹里整理好。素材比较倾向规律的整理。比如 文件夹结构   字体\中文字体\方正字体\类黑体（类宋体\艺术字……） ，使用时也多半是文件直接剪切或者拷贝到素材库的类目里。所以，在往库里添加素材的时候，是关联连接地址，还是直接移动文件，或者可以自选之类的
3、公众号看到的时候说是要换编写语言？虽然是个大工程，但是还是想问一下大概什么时候要换或者能重构好？

**Comment by hunmer** [comment]
你好！关于你的问题
1.billfish会偏向企业版没有办法，因为个人版已经能够满足大部分的需求，再对不赚钱的产品进行迭代升级，可能对现有的口碑会有影响。。（比如说这个2.0到3.0版本的升级，不满意的人占多数）
2.默认的数据结构是私有制的（xx/xx/xxxx），是为了保证使用资源管理器打开某个有大量文件夹的文件不会奔溃卡死。类似billfish结构那样跟目录文件夹保持一致的插件也有。读billfish或eagle的素材库标签的插件也有（之前测试成功了，没什么人使用不保证没有bug），导入文件也包含链接文件，移动文件，或者复制文件，相比于billfish的优势可能就是导入的时候可以根据插件规则来自定义导入方式，不用去资源库来回设置导入方式吧
3.没有换编写语言的打算，因为根本还没有完善。。。这个软件主要是个人也有这方面的需求，所以功能也是一点一点加的，但软件自带的开放性支持用户自己去添加或者修改功能，比较适合那些喜欢折腾或自定义私有素材库的人使用吧
以上都是个人观点，欢迎讨论！
